trigger: none

stages:
  - stage: build
    displayName: build stage
    pool: ubuntu-latest
    jobs:
      - job: buildJob
        steps:
          - task: Npm@1
            inputs:
              command: 'install'

          - task: Npm@1
            inputs:
              command: 'custom'
              customCommand: 'run build'
  
          - task: PublishBuildArtifacts@1
            inputs:
              PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
              ArtifactName: 'build_$(Build.BuildId)'
              publishLocation: 'Container'

          - task: UniversalPackages@0
            inputs:
              command: 'publish'
              publishDirectory: '$(System.DefaultWorkingDirectory)/build'
              feedsToUsePublish: 'internal'
              vstsFeedPublish: 'a7ddfc6d-3498-4ec3-94bf-db09610f3c2a/a7c940f9-63f9-4564-9d12-3d60c40b9a7d'
              vstsFeedPackagePublish: 'todo-build'
              versionOption: 'patch'

              